#!/bin/sh
echo "[husky] Updating lint-diff-files.txt..."

git diff --name-only --diff-filter=ACMRTUXB HEAD | grep -E '\.tsx?$' >> lint-diff-files.txt || true
sort -u lint-diff-files.txt -o lint-diff-files.txt

echo "[husky] Tracked changed files:"
cat lint-diff-files.txt


git add lint-diff-files.txt