name: My Next.js CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - '**'

jobs:
  lint:
    uses: hironobugt/my-app/.github/workflows/common.yml@main
    with:
      lint_script: ./lint.sh
