name: My Next.js CI

on:
  pull_request:
    branches:
      - feature/*

jobs:
  get-diff:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.diff.outputs.files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: diff
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- '*.ts' '*.tsx' | paste -sd' ' -)" >> $GITHUB_OUTPUT

