name: Delete lint-diff.txt on PR merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: write  # 必須

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merged branch (base branch)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove lint-diff-files.txt if it exists
        run: |
          if [ -f lint-diff-files.txt ]; then
            git rm lint-diff-files.txt
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: remove lint-diff-files.txt after PR merge"
            git push
          else
            echo "lint-diff-files.txt not found"
          fi
