name: Delete lint-diff.txt on PR merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: write  # 必須

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merged branch (base branch)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove lint-diff-files.txt if it exists
        run: |
          FILES_TO_DELETE=()
          for FILE in lint-diff-files.txt related-files.txt; do
            if [ -f "$FILE" ]; then
              git rm "$FILE"
              FILES_TO_DELETE+=("$FILE")
            fi
          done
          if [ ${#FILES_TO_DELETE[@]} -gt 0 ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: remove ${FILES_TO_DELETE[*]} after PR merge"
            git push
          else
            echo "No files to delete"
          fi
